### PR TITLE
Documentation and Bugfix

### PR DESCRIPTION
**Pull request by ycheng627**

### CODE REVIEW

**Review by BaiiYuan — APPROVED** [review]
Overall LGTM. Please let me know if you need revisit/review of Wiki (LGTM at first glance).

**Comment by ycheng627** [comment]
Please also review the wiki page! 

You can edit the wiki page on github directly, so feel free to change anything that you see, or reply here if you have questions or concerns.

**Comment by BaiiYuan** [comment]
`[Tutorial] Post‐Login` is verified and updated after testing.

**Review by cyhuang1230 — APPROVED** [review]
LGTM

**Pull request merged**
