### PR TITLE
[License] Add all missing license

### PR DESCRIPTION
**Pull request by ycheng627**
[License] Add BSD-3 according to Google open source guidance

For all .ts, .js, .css and .html files located in the source directory, ensure they have a valid BSD-3 license.

Some files already have a chromium license, switch to the BSD-3 version.

### CODE REVIEW

**Comment by BaiiYuan** [comment]
Overall LGTM.

Is there any requirement or ticket of this? I am curious why we use chromium license.

**Comment by BaiiYuan** [comment]
Is there any requirement or ticket of this? I am curious why we use chromium license.

BTW, it seems that the license in this repo is BSD.

**Review by BaiiYuan — APPROVED** [review]
Overall LGTM as we have existing files using Chromium license header.

**Comment by ycheng627** [comment]
Hi Reviewer,

PTAL at the CL again. Note that I will squash-merge this PR to prevent versions without license. This is just to help review of the files easier.

**Review by BaiiYuan — APPROVED** [review]

**Pull request merged**
